### ISSUE TITLE
World is not saved when killing the game

### ISSUE THREAD

**Issue by Oondanomala** [KingContaria/FastQuit#13]
If the game is killed (eg. alt f4) the world is not saved and all progress since the last save is lost.
In vanilla the world is saved before closing the game.

Minecraft 1.19.3

**Comment by KingContaria** [comment]
oh god, fix coming soon!

**Comment by KingContaria** [comment]
https://modrinth.com/mod/fastquit/version/1.3.0

will port to other versions shortly

**Comment by Oondanomala** [comment]
Even with the last version the world is still not fully saved when killing it with task manager (alt f4 now works fine tho).
It seems like it saves halfway because if i place some blocks and then kill it half of the blocks remain but the other half doesn't. Also, the player position gets reset.

**Comment by KingContaria** [comment]
that is very weird, i'll look into that. does it save fully with vanilla?

**Comment by Oondanomala** [comment]
I think so, but i cannot test right now

**Comment by KingContaria** [comment]
no worries, i'll test it out tomorrow i think

**Comment by KingContaria** [comment]
okay so i can confirm the issue, but its also happening in vanilla for me, so its probably minecrafts or the taskmanagers fault?

**Comment by Oondanomala** [comment]
If it's a vanilla issue i wouldn't bother trying to fix it (unless it's super easy).
When i get back i will do some more testing and see (i thought that didn't happen in vanilla, but i was probably wrong), but for now i can't do anything

**Comment by KingContaria** [comment]
yea i'm interested in why it happens now, i'll look into it at some point, for now enjoy the holidays! :)

**Comment by KingContaria** [comment]
okay so im pretty sure the task manager problem is just because of how the taskmanager kills the process and theres not really something i could do about it and since its in vanilla too im just gonna leave it like that. thanks for your help! :)

**Comment by Oondanomala** [comment]
Glad to help, and thanks for testing it! :D
