### ISSUE TITLE
World disappears when saving

### ISSUE THREAD

**Issue by Felix14-v2** [KingContaria/FastQuit#3]
Now FastQuit hides the world from the list for the time of saving. this can greatly frighten a player who accidentally notices that his world has disappeared.

Instead, it makes sense to block the loading of the world that is currently being saved, while adding the mark "blocked during saving" to it. Similar to how it is happening now in vanilla with the label "blocked by another running Minecraft".

**Comment by KingContaria** [comment]
Hm, not showing it is just what minecraft does by default, i'll have to look into how to modify that. I'll definitely give it a try tho!

**Comment by KingContaria** [comment]
Okay i think ive got something pretty nice working, it will show the world as normal but when you try to load it it will wait for the world to finish saving (similar to when closing minecraft, it will also open a screen with a "Waiting for x to finish saving...")

**Comment by KingContaria** [comment]
fixed in [0.4.0](https://modrinth.com/mod/fastquit/version/0.4.0)

**Comment by Felix14-v2** [comment]
Nice!

> adding the mark "blocked during saving" to it. Similar to how it is happening now in vanilla with the label "blocked by another running Minecraft".

I meant this:
![Locked](https://user-images.githubusercontent.com/75726196/201972893-13f6962d-d198-4d6b-8167-e8cdb86c7f4b.png)

**Comment by KingContaria** [comment]
yea i figured you meant that, the approach i took just turned out to be very easy and clean, which is why i personally prefer it
