### ISSUE TITLE
Update to 1.21.2

### ISSUE THREAD

**Issue by Thijzert123** [KingContaria/FastQuit#53]
1.21.2/1.21.3 support would be nice. Thanks!

**Comment by ImGRUI** [comment]
It works on 1.21.2/3, but probably would crash on leaving Realms (mixin failure with modernfix force load).
Did you test it before writing an issue?

**Comment by Thijzert123** [comment]
Hi, I'm sorry about that. I saw on Modrinth that the mod isn't supported for 1.21.2, so I tried forking and compiling with new versions. I got lots of error messages (classes, methods not found, etc.), so I figured it didn't work on 1.21.2. Thanks!
