### ISSUE TITLE
Disable "Quit game" button to prevent unsaved world

### ISSUE THREAD

**Issue by SkyWors** [KingContaria/FastQuit#7]
A simple suggestion to avoid quitting the game too quickly with the "Quit game" button without giving it time to properly finish saving the world.

Maybe with a tooltip message "The world is not currently saved" when hovering with cursor.

![image](https://user-images.githubusercontent.com/70440695/203087525-bea176fc-b7aa-4e14-8f24-cff7ae6d08d2.png)

**Comment by KingContaria** [comment]
Not sure how useful that would be tbh, since if you do quit it will just wait for the world to save anyway?

**Comment by SkyWors** [comment]
Quitting the game while the world is not saved will interrupt the process and potentially corrupt it. Like Alt+F4 the window during the saving process.

**Comment by KingContaria** [comment]
That is not the case, when you close the game (tested with Alt+F4, quit button, window X and crash) the mod has a failsave implemented and will wait for the saving world to finish before closing Minecraft

![fastquit2](https://user-images.githubusercontent.com/98704937/203093053-a91c1531-4af7-4c0a-ac28-5ad23d6ef763.gif)

**Comment by SkyWors** [comment]
Indeed, I had not succeeded in triggering this process on the first try. So I close my exit :D. Excellent mod!
